/**
 * icon.ts — Embedded tray icon (base64-encoded ICO, 32x32, fully opaque).
 *
 * Brand teal (#7fd6c4) field + dark activity-pulse glyph + 2px dark border, on
 * a fully OPAQUE alpha channel (the previous icon was generated at ~50% alpha
 * and rendered invisibly in the Windows tray — BUG-010). Regenerated by a
 * deterministic builder (32bpp BGRA, all-zero AND mask).
 *
 * systray2 uses the value verbatim as base64 when it is not an existing file
 * path, so embedding avoids a runtime file dependency.
 */

export const TRAY_ICON_BASE64 =
  "AAABAAEAICAAAAEAIACoEAAAFgAAACgAAAAgAAAAQAAAAAEAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAfIBL/HyAS/x8gEv8fIBL/HyAS/x8gEv8fIBL/HyAS/x8gEv8fIBL/HyAS/x8gEv8fIBL/HyAS/x8g" +
  "Ev8fIBL/HyAS/x8gEv8fIBL/HyAS/x8gEv8fIBL/HyAS/x8gEv8fIBL/HyAS/x8gEv8fIBL/HyAS/x8g" +
  "Ev8fIBL/HyAS/x8gEv8fIBL/HyAS/x8gEv8fIBL/HyAS/x8gEv8fIBL/HyAS/x8gEv8fIBL/HyAS/x8g" +
  "Ev8fIBL/HyAS/x8gEv8fIBL/HyAS/x8gEv8fIBL/HyAS/x8gEv8fIBL/HyAS/x8gEv8fIBL/HyAS/x8g" +
  "Ev8fIBL/HyAS/x8gEv8fIBL/HyAS/x8gEv/E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TW" +
  "f//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TW" +
  "f//E1n//xNZ//8TWf//E1n//HyAS/x8gEv8fIBL/HyAS/8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TW" +
  "f//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TW" +
  "f//E1n//xNZ//8TWf//E1n//xNZ//8TWf/8fIBL/HyAS/x8gEv8fIBL/xNZ//8TWf//E1n//xNZ//8TW" +
  "f//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TW" +
  "f//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//x8gEv8fIBL/HyAS/x8gEv/E1n//xNZ//8TW" +
  "f//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TW" +
  "f//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//HyAS/x8gEv8fIBL/HyAS/8TW" +
  "f//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TW" +
  "f//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf/8fIBL/HyAS/x8g" +
  "Ev8fIBL/xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TW" +
  "f//E1n//HyAS/8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//x8g" +
  "Ev8fIBL/HyAS/x8gEv/E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TW" +
  "f//E1n//xNZ//8TWf/8fIBL/xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TW" +
  "f//E1n//HyAS/x8gEv8fIBL/HyAS/8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TW" +
  "f//E1n//xNZ//8TWf//E1n//HyAS/x8gEv8fIBL/xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TW" +
  "f//E1n//xNZ//8TWf/8fIBL/HyAS/x8gEv8fIBL/xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TW" +
  "f//E1n//xNZ//8TWf//E1n//xNZ//8TWf/8fIBL/xNZ//x8gEv/E1n//xNZ//8TWf//E1n//xNZ//8TW" +
  "f//E1n//xNZ//8TWf//E1n//xNZ//x8gEv8fIBL/HyAS/x8gEv/E1n//xNZ//8TWf//E1n//xNZ//8TW" +
  "f//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//x8gEv/E1n//HyAS/x8gEv/E1n//xNZ//8TW" +
  "f//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//HyAS/x8gEv8fIBL/HyAS/8TWf//E1n//xNZ//8TW" +
  "f//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//HyAS/8TWf//E1n//HyAS/8TW" +
  "f//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf/8fIBL/HyAS/x8gEv8fIBL/xNZ//8TW" +
  "f//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//x8gEv8fIBL/xNZ//8TW" +
  "f/8fIBL/xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//x8gEv8fIBL/HyAS/x8g" +
  "Ev/E1n//xNZ//8TWf/8fIBL/HyAS/x8gEv8fIBL/HyAS/x8gEv/E1n//xNZ//8TWf//E1n//HyAS/8TW" +
  "f//E1n//xNZ//x8gEv8fIBL/xNZ//8TWf//E1n//HyAS/x8gEv8fIBL/HyAS/8TWf//E1n//HyAS/x8g" +
  "Ev8fIBL/HyAS/8TWf//E1n//xNZ//x8gEv8fIBL/HyAS/x8gEv8fIBL/HyAS/8TWf//E1n//xNZ//8TW" +
  "f/8fIBL/xNZ//8TWf//E1n//xNZ//x8gEv/E1n//xNZ//x8gEv8fIBL/HyAS/x8gEv8fIBL/xNZ//8TW" +
  "f/8fIBL/HyAS/x8gEv8fIBL/xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf/8fIBL/HyAS/8TW" +
  "f//E1n//HyAS/x8gEv/E1n//xNZ//8TWf//E1n//HyAS/x8gEv8fIBL/HyAS/8TWf//E1n//xNZ//8TW" +
  "f//E1n//xNZ//x8gEv8fIBL/HyAS/x8gEv/E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TW" +
  "f/8fIBL/xNZ//8TWf/8fIBL/xNZ//8TWf//E1n//xNZ//8TWf//E1n//HyAS/x8gEv/E1n//xNZ//8TW" +
  "f//E1n//xNZ//8TWf//E1n//HyAS/x8gEv8fIBL/HyAS/8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TW" +
  "f//E1n//xNZ//x8gEv8fIBL/xNZ//x8gEv/E1n//xNZ//8TWf//E1n//xNZ//8TWf/8fIBL/xNZ//8TW" +
  "f//E1n//xNZ//8TWf//E1n//xNZ//8TWf/8fIBL/HyAS/x8gEv8fIBL/xNZ//8TWf//E1n//xNZ//8TW" +
  "f//E1n//xNZ//8TWf//E1n//xNZ//x8gEv/E1n//HyAS/8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TW" +
  "f//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//x8gEv8fIBL/HyAS/x8gEv/E1n//xNZ//8TW" +
  "f//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//HyAS/x8gEv8fIBL/xNZ//8TWf//E1n//xNZ//8TW" +
  "f//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//HyAS/x8gEv8fIBL/HyAS/8TW" +
  "f//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//HyAS/8TWf//E1n//xNZ//8TW" +
  "f//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf/8fIBL/HyAS/x8g" +
  "Ev8fIBL/xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf/8fIBL/xNZ//8TW" +
  "f//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//x8g" +
  "Ev8fIBL/HyAS/x8gEv/E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TW" +
  "f//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TW" +
  "f//E1n//HyAS/x8gEv8fIBL/HyAS/8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TW" +
  "f//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TW" +
  "f//E1n//xNZ//8TWf/8fIBL/HyAS/x8gEv8fIBL/xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TW" +
  "f//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TW" +
  "f//E1n//xNZ//8TWf//E1n//xNZ//x8gEv8fIBL/HyAS/x8gEv/E1n//xNZ//8TWf//E1n//xNZ//8TW" +
  "f//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TW" +
  "f//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//HyAS/x8gEv8fIBL/HyAS/8TWf//E1n//xNZ//8TW" +
  "f//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TW" +
  "f//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf/8fIBL/HyAS/x8gEv8fIBL/xNZ//8TW" +
  "f//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TW" +
  "f//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//x8gEv8fIBL/HyAS/x8g" +
  "Ev/E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TW" +
  "f//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//xNZ//8TWf//E1n//HyAS/x8g" +
  "Ev8fIBL/HyAS/x8gEv8fIBL/HyAS/x8gEv8fIBL/HyAS/x8gEv8fIBL/HyAS/x8gEv8fIBL/HyAS/x8g" +
  "Ev8fIBL/HyAS/x8gEv8fIBL/HyAS/x8gEv8fIBL/HyAS/x8gEv8fIBL/HyAS/x8gEv8fIBL/HyAS/x8g" +
  "Ev8fIBL/HyAS/x8gEv8fIBL/HyAS/x8gEv8fIBL/HyAS/x8gEv8fIBL/HyAS/x8gEv8fIBL/HyAS/x8g" +
  "Ev8fIBL/HyAS/x8gEv8fIBL/HyAS/x8gEv8fIBL/HyAS/x8gEv8fIBL/HyAS/x8gEv8fIBL/HyAS/x8g" +
  "Ev8fIBL/HyAS/x8gEv8fIBL/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
